### ISSUE TITLE
Raspberry Pi Zero

### ISSUE THREAD

**Issue by Luuii** [googlecreativelab/coder#103]
Do you know if the Coder works into the new Raspberry PI Zero ?

**Comment by jmstriegel** [comment]
@Luuii I haven't yet been able to test on the Pi Zero, but I expect it will function similar to the original Pi B. The one complication is that without built-in ethernet, you might not have a handy way to access the device is wireless is misbehaving. If you end up giving it a shot, let me know how things work out.
