### ISSUE TITLE
Plugin/extension library

### ISSUE THREAD

**Issue by Stijn-Flipper** [googlecreativelab/coder#26]
I've seen many issues asking for additional support for `this language` and `that one` too. It should be really awesome to support other awesome languages like `python` or `ruby`, *but*...

I also appreciate the KISS principle ( **K**eep **I**t **S**tupidly **S**imple ) that's handled here. Many new-to-the-programming-world are often too scared of the bunch of languages (or featurettes) supported in the Coder project, like learning one programming language isn't difficult enough for them (it *isn't* difficult, we all know, but they don't). 

Therefore, I suggest to create something like a plugin/extension-library (like [Chrome web store](https://chrome.google.com/webstore/category/extensions) ), so that when the user gets more confident and experienced with hacking (or is already experienced), they can download plugins for supporting other languages they want to learn it too (or some other pretty cool extensions - Vim support, Git support, to get some ideas..) into the RPi Coder instead of pumping the Coder project full of support/extensions they problably never use it anyway...

**Comment by whinge** [comment]
when I get a computer to run arduino without talking to me like it is a bunch of geeks from Indian continent
I may find the time to learn the C++ etc.
