### ISSUE TITLE
Updating Coder

### ISSUE THREAD

**Issue by isaacrg** [googlecreativelab/coder#44]
Just, a thought, how would you update coder, in-app?
I am only thinking about the core node.js app, would it be possible for a notification, on login, with a single-click update process?

**Comment by jmstriegel** [comment]
FYI - the latest image has an updated version of Node.  It's sort of a pain to install because it needs to be done manually and copied to /opt/node/. Unfortunately, the apt-get version is really old.

**Comment by whinge** [comment]
what is a node?  who or what is Coder? I just do not understand the words being used, I am an old hobbyist with Arduino and Raspberry but two PC's with faults!
 means starting all over as most projects disappeared with two house moves on top of faulty PC's.
I am only trying to get sensors and key pads to work.  but  for some reason  # Keypad.h downloaded from
Arduino website is not recognised,up to this point.   latest IDE downloaded last night may now work?
passwords for Raspberry may now be hard to remember?
