### ISSUE TITLE
GPIO pins inaccessible via fs.js and user coder permissions, PI-GPIO

### ISSUE THREAD

**Issue by mrutgerj** [googlecreativelab/coder#48]
I have been experimenting with pi-gpio version 0.0.2, and node version 10.9
There seems to be a permissions problem. The call to define a pin works:

> gpio.open(16, function(err, value) {
>       if(err) throw err;
>        console.log(value);    // The current state of the pin
>    });

It uses gpio-admin and the node fs.js to accomplish this. It results in permissions:

> -rw------- 1 coder coder 4096 Oct  5 08:18 value

However, when we want to execute a gpio.read command, it eventually ends up at this call in fs.js, line 284

> var fd = fs.openSync(path, flag, 438 /_=0666_/);

EDIT: this is the same in version of nodejs distributed with coder.

I tried setting the optional flag 'r', which it defaults to anyway. But editing the source of a node fs.js, I would rather not do. 

I can get pi-gpio to succeed in reading the value by chmod'ing to 666. 

So, what would the proper resolution to get IO going on this platform - a default umask for the coder user on that directory?

Any help greatly appreciated. I really want to get going with actually building a web UI instead of chasing down the inner-workings, however interesting it is.

**Comment by JamesNewton** [comment]
Or you can 

```
cd coder-base/node_modules
npm install gpio

```
