### ISSUE TITLE
changing hostname on windows

### ISSUE THREAD

**Issue by jrobinson-uk** [googlecreativelab/coder#80]
Having just setup a class set of coder devices it was a pain to find that windows notepad was adding in line breaks so:

Coder01

became

Coder
01

and therefore didn't work.

I ended up booting the pi and editing the hostname file in nano which worked. Is there a way round this in windows? Perhaps some more detailed instruction could be given for some who may stumble at this hurdle

**Comment by jmstriegel** [comment]
With the latest version, you can edit the hostname and hosts file in the boot directory. If you put the sdcard in your windows machine, look inside the coder_settings directory for hosts.txt and hostname.txt. Be sure to use a code editor with unix-style newlines. You can edit these to what you need, and Coder will pull in the new settings when it boots.
