### ISSUE TITLE
Your card wasn't correctly detected. Let's try again

### ISSUE THREAD

**Issue by eliasnogueira** [googlecreativelab/coder#9]
I'm trying to install Coder in SD card using SDFormatter like I do in my SD cards to install Raspberry Pi distros in raspberrypi.org

All the time I get "Your card wasn't correctly detected. Let's try again".

Environment:
MacOSX 10.8.5
SD Card Element 14 4GB formatted in FAT-32

![screenshot](https://f.cloud.github.com/assets/284888/1143741/8b28f5bc-1d56-11e3-8f19-2bfe437a2f4d.png)

**Comment by erwinlauener** [comment]
I'm keen on running Coder but the same issue occurs.
- raspberry pi2B
- SanDisk Extreme micro SDHC UHS-I 32GB Card (recommended by a test)

I followed your hints above but "Your card wasn't correctly detected. Let's try again" is returned always...

Thanks for your help a lot!
