### ISSUE TITLE
Login ?

### ISSUE THREAD

**Issue by nathan30** [googlecreativelab/coder#98]
Hi,

I try to install Coder. So I download the .img and flash it with Win32DiskImager

I put the SD on my RPI B, boot it. A lot of line appear, and at the end it ask to login ; 

"Raspbian GNU/Linux 7 coder tty1
coder login : 
"

I try coder as login and same as password. 

How I can pass this ?

THanks in advance

**Comment by whinge** [comment]
Refer that to the official web site of Raspberry pi?
Or try git hub.com

**Comment by nathan30** [comment]
I found it ; 

login : pi 
passwd : raspberry
